### PR TITLE
Run React and Node App at same time

### PR DESCRIPTION
**Pull request by rquinones93**
Installed concurrently node module

This module allows us to run multiple scripts at once

Added 'dev' script which runs React App and Node App simultaneously

Right now Master doesn't have updates to display the DB data to the front end, but once Jesus's PR is merged it will work fine.

Run `yarn dev` from the doc root and hit localhost:3001/announcements and you'll get the JSON back

### CODE REVIEW

**Comment by rquinones93** [comment]
I don't know how to fix these locks uhhhhh

**Comment by j-palos** [comment]
> I don't know how to fix these locks uhhhhh

I'll fix it, one sec.

**Review by j-palos — CHANGES_REQUESTED** [review]
yarn run v1.13.0
$ concurrently "yarn start" "yarn --cwd ./backend start:dev"
/bin/sh: concurrently: command not found
error Command failed with exit code 127.

I get this error trying to run this. Not sure why?

**Review by j-palos — APPROVED** [review]

**Comment by j-palos** [comment]
Looks good. You can merge this into master.

**Pull request merged**
